defaults:
  - model@lgb: lgb
  - _self_

data:
  train_path: "../data/input/train.csv"
  test_path: "../data/input/test.csv"
  submission_path: "../data/input/sample_submission.csv"
  output_path: "../data/output/"
  model_path: "../data/model/"

seed: 42
n_splits: 5
